# Generated by Django 2.0.1 on 2018-12-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=52, max_length=254),
            preserve_default=False,
        ),
    ]
